# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:12
    container_name: psql-12
    environment:
      POSTGRES_PASSWORD: "tim"
    volumes:
      - ./backups:/tmp/backup
      - ./pgdata:/var/lib/postgresql/data
