# docker-compose.yml
version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysql-8-copy
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
      - ./backups:/tmp/backup
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=tim
      - MYSQL_DATABASE=test_db
