# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:13
    container_name: psql-13
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
